#:schema node_modules/wrangler/config-schema.json
name = "tonstar-bot"
main = "src/index.ts"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
	{ binding = "tstars_user_meta", id = "ac143a122346435a8485a596d7afab62" },
]

[vars]
BOT_INFO = """{
	"id":7412130867,
	"is_bot":true,
	"first_name":"TON Stars DAO",
	"username":"TONStarsDAObot",
	"can_join_groups":true,
	"can_read_all_group_messages":true,
	"supports_inline_queries":false,
	"can_connect_to_business":false
}"""
